server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration,org.springframework.boot.actuate.autoconfigure.metrics.web.servlet.WebMvcMetricsAutoConfiguration,org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/coze_timer?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
        max-wait: 1000

# OpenAPI配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
  packages-to-scan: com.coze.timer.controller

# 完全禁用Spring Boot Actuator功能
management:
  metrics:
    enable:
      all: false
      process: false
      process.cpu: false
      system.cpu: false
    export:
      simple:
        enabled: false
    web:
      server:
        auto-time-requests: false
    binders:
      processor:
        enabled: false
      jvm:
        enabled: false
      system:
        enabled: false
  endpoint:
    health:
      enabled: false
  endpoints:
    enabled-by-default: false
    jmx:
      enabled: false
    web:
      exposure:
        include: none

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coze.timer.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.coze.timer: info
    org.springframework: warn
    com.coze.timer.mapper: debug

# 定时器配置
timer:
  # 是否启用分布式模式
  distributed: false
  # 执行器配置
  executor:
    # HTTP客户端连接池大小
    http-pool-size: 200
    # 连接超时(毫秒)
    connect-timeout: 5000
    # 请求超时(毫秒)
    request-timeout: 15000
    # 默认重试次数
    retry-count: 3
    # 令牌桶配置
    rate-limiter:
      enabled: true
      capacity: 100
      refill-rate: 10
  
  # ZooKeeper配置
  zookeeper:
    host: localhost
    port: 2181
    session-timeout: 60000
    connection-timeout: 15000
    base-path: /coze/timer 