version: '3'

# Springboot and MySQL services
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coze-timer-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coze_timer?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - coze-timer-network

  mysql:
    image: mysql:8.0
    container_name: coze-timer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coze_timer
      MYSQL_USER: coze
      MYSQL_PASSWORD: coze123
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - coze-timer-network

volumes:
  mysql-data:

networks:
  coze-timer-network:
    driver: bridge

# 注意：SpringDoc Swagger UI 可以通过以下URL访问:
# - Swagger UI: http://localhost:8080/swagger-ui/index.html 
# - OpenAPI 规范: http://localhost:8080/v3/api-docs 